language: python

install:
  - pip install pylint

python:
  - '2.7'
  - '3.6'

branches:
  only:
  - master

script: pylint --disable=I,C,R,logging-not-lazy,wildcard-import,unused-wildcard-import,fixme,broad-except,bare-except,eval-used,exec-used,global-statement,logging-format-interpolation,no-name-in-module,import-error